import "./globals.css";
import { CatagoryContextPovider } from "./context/catagoryContext";
import { ProductContextPovider } from "./context/productContext";
import { UserContextPovider } from "./context/userContext";
import TopNav from "./components/topnav";

export const metadata = {
  title: "e-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <CatagoryContextPovider>
        <ProductContextPovider>
          <UserContextPovider>
            <body>
              <TopNav />
              {children}
            </body>
          </UserContextPovider>
        </ProductContextPovider>
      </CatagoryContextPovider>
    </html>
  );
}
